import { publishedContent } from '../server/domain/portfolio.mjs';
import { youtubeId } from './content-model.js';
export const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
const e = escape;
const external = 'target="_blank" rel="noopener noreferrer"';
const image = (src, alt, cls = '') => src ? `<img src="${e(src)}" alt="${e(alt)}" loading="lazy" class="${cls}">` : '';
const link = (label, url, cls = 'link') => url && label ? `<a class="${cls}" href="${e(url)}" ${/^https?:/.test(url) ? external : ''}>${e(label)}</a>` : '';
const buttons = rows => rows.map(b => link(b.label, b.url, `btn btn--${b.style}`)).join('');
const empty = (s, rows) => rows || (s.emptyText ? `<p class="empty-work">${e(s.emptyText)}</p>` : '');
const head = s => `<div class="sectionHead reveal"><div>${s.eyebrow ? `<div class="section__eyebrow">${e(s.eyebrow)}</div>` : ''}${s.title ? `<h2 class="section__title">${e(s.title)}</h2>` : ''}${s.description ? `<p class="section__lead">${e(s.description)}</p>` : ''}</div></div>`;
const section = (id, s, inner) => `<section class="section" id="${id}" aria-label="${e(s.navLabel || s.title)}"><div class="container">${head(s)}${inner}</div></section>`;
const rgb = hex => [1, 3, 5].map(i => parseInt(hex.slice(i, i + 2), 16)).join(',');

export function renderPortfolio(c) {
  c = publishedContent(c);
  const nav = c.order.filter(id => c[id].settings.enabled && c[id].settings.navLabel).map(id => `<a href="#${id}" data-drawer-link>${e(c[id].settings.navLabel)}</a>`).join('');
  const resume = c.site.resume ? `<a class="btn btn--ghost" href="${e(c.site.resume)}" download data-drawer-link>${e(c.site.resumeLabel)}</a>` : '';
  const sectionHtml = {
    about: () => section('about', c.about.settings, `<div class="grid-2"><div class="card card--glass reveal">${empty(c.about.settings, c.about.biography ? `<p class="section__lead">${e(c.about.biography)}</p>` : '')}<div class="stats">${c.about.stats.map(s => `<div class="stat"><div class="stat__num">${e(s.value)}</div><div class="stat__label">${e(s.label)}</div></div>`).join('')}</div><div class="about__actions">${buttons(c.about.buttons)}${resume}</div></div><div class="about__profile reveal">${c.about.photo ? `<div class="profileFrame">${image(c.about.photo, c.about.photoAlt)}${c.about.badgeTitle || c.about.badgeSubtitle ? `<div class="profileFrame__badge"><div class="profileFrame__badgeTitle">${e(c.about.badgeTitle)}</div><div class="profileFrame__badgeSub">${e(c.about.badgeSubtitle)}</div></div>` : ''}</div>` : ''}<div class="miniCards">${c.about.details.map(d => `<div class="miniCard"><div class="miniCard__title">${e(d.title)}</div><div class="miniCard__text">${e(d.description)}</div></div>`).join('')}</div></div></div>`),
    showreel: () => section('showreel', c.showreel.settings, `${link(c.showreel.channelLabel, c.showreel.channelUrl, 'btn btn--ghost')}${empty(c.showreel.settings, c.showreel.videos.length ? `<div class="reelGrid">${c.showreel.videos.map(v => { const id = youtubeId(v.youtubeUrl); return `<button class="reelCard reveal" data-video-id="${id}" type="button" aria-label="${e(v.title || 'Play video')}">${image(v.thumbnail || (id ? `https://i.ytimg.com/vi/${id}/hqdefault.jpg` : ''), v.title)}<div class="reelCard__overlay"><div class="reelCard__title">${e(v.title)}</div><div class="reelCard__meta">${e(v.category)}</div></div><span class="reelCard__play" aria-hidden="true">▶</span></button>`; }).join('')}</div>` : '')}`),
    projects: () => section('projects', c.projects.settings, projectExplorer(c)),
    gallery: () => section('gallery', c.gallery.settings, empty(c.gallery.settings, c.gallery.pictures.length ? `<div class="gallery-grid">${c.gallery.pictures.map(p => `<figure class="gallery-card reveal">${image(p.image, p.alt || p.title)}<figcaption><h3>${e(p.title)}</h3><p>${e(p.caption)}</p></figcaption></figure>`).join('')}</div>` : '')),
    skills: () => section('skills', c.skills.settings, empty(c.skills.settings, c.skills.groups.length ? `<div class="skillsGrid">${c.skills.groups.map(g => `<div class="skillPanel reveal"><div class="skillPanel__title">${e(g.title)}</div>${g.items.map(s => `<div class="skillBar" data-level="${s.level}"><div class="skillBar__head"><span>${e(s.name)}</span><span class="skillBar__pct">${s.level}%</span></div><div class="skillBar__track"><div class="skillBar__fill" style="width:${s.level}%"></div></div></div>`).join('')}</div>`).join('')}</div>` : '')),
    experience: () => section('experience', c.experience.settings, empty(c.experience.settings, c.experience.items.length ? `<div class="timeline">${c.experience.items.map(t => `<div class="timeItem reveal"><div class="timeItem__dot"></div><div class="timeItem__top"><div class="timeItem__role">${e(t.title)}</div><div class="timeItem__time">${e(t.period)}</div></div><div class="timeItem__desc">${e(t.description)}</div></div>`).join('')}</div>` : '')),
    achievements: () => section('achievements', c.achievements.settings, empty(c.achievements.settings, c.achievements.items.length ? `<div class="badgeGrid">${c.achievements.items.map(a => `<div class="badgeCard reveal"><div class="badgeCard__icon">${e(a.icon)}</div><div class="badgeCard__title">${e(a.title)}</div><div class="badgeCard__text">${e(a.description)}</div><div class="badgeList">${a.links.map(l => link(l.label, l.url, 'badgeList__item')).join('')}${link(a.certificateLabel, a.certificate, 'badgeList__item')}</div></div>`).join('')}</div>` : '')),
    contact: () => section('contact', c.contact.settings, `<div class="contactList">${empty(c.contact.settings, c.contact.items.map(i => i.url ? `<a class="contactItem" href="${e(i.url)}" ${/^https?:/.test(i.url) ? external : ''}><span class="contactItem__k">${e(i.label)}</span><span class="contactItem__v">${e(i.value)}</span></a>` : `<div class="contactItem"><span class="contactItem__k">${e(i.label)}</span><span class="contactItem__v">${e(i.value)}</span></div>`).join(''))}</div>`),
  };
  const title = c.hero.title, offset = c.hero.highlight ? title.indexOf(c.hero.highlight) : -1;
  const headline = offset < 0 ? e(title) : `${e(title.slice(0, offset))}<span class="gold">${e(c.hero.highlight)}</span>${e(title.slice(offset + c.hero.highlight.length))}`;
  const a = c.appearance;
  return `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(c.site.title)}</title><meta name="description" content="${e(c.site.description)}"><meta name="author" content="${e(c.site.name)}"><meta name="keywords" content="${e(c.site.keywords)}"><meta name="theme-color" content="${a.background}"><meta property="og:title" content="${e(c.site.title)}"><meta property="og:description" content="${e(c.site.description)}"><meta property="og:type" content="website">${c.site.socialImage ? `<meta property="og:image" content="${e(c.site.socialImage)}">` : ''}<link rel="icon" href="${e(c.site.favicon || '/assets/favicon.svg')}"><link rel="stylesheet" href="/assets/fonts/fonts.css"><link rel="stylesheet" href="/styles/main.css?v=20261007-menu"></head>
    <body class="${a.motion ? 'with-motion' : 'no-motion'}" style="--gold:${a.accent};--gold2:${a.accentDark};--accent-rgb:${rgb(a.accent)};--accent-dark-rgb:${rgb(a.accentDark)};--bg:${a.background};--bg2:${a.backgroundEnd};--bg-rgb:${rgb(a.background)};--text-rgb:${rgb(a.text)};--text:${a.text};--radius2:${a.rounded}px;--radius:${Math.max(0, a.rounded - 8)}px;--body-font:${a.font};--heading-font:${a.headingFont}">
    ${c.hero.introEnabled && a.motion ? `<div class="intro" id="intro" aria-hidden="true"><div class="intro__grain"></div><div class="intro__inner"><div class="intro__mark"><span class="intro__gold">${e(c.hero.introPrimary)}</span><span class="intro__white">${e(c.hero.introSecondary)}</span></div><div class="intro__line"></div><div class="intro__sub">${e(c.hero.introMessage)}</div></div></div>` : ''}
    ${a.cursor ? '<div class="cursor" id="cursor" aria-hidden="true"></div><div class="cursor-glow" id="cursorGlow" aria-hidden="true"></div>' : ''}
    <header class="nav" id="top"><a class="nav__brand" href="#top" aria-label="Go to top"><span class="nav__brandDot"></span><span class="nav__brandText">${e(c.site.brand)}</span></a><nav class="nav__links" aria-label="Primary">${nav}</nav><div class="nav__actions">${resume}<button class="nav__menu" id="menuBtn" aria-label="Open menu" aria-expanded="false" aria-controls="drawer"><span></span><span></span><span></span></button></div></header>
    <aside class="drawer" id="drawer" aria-hidden="true" inert><div class="drawer__panel"><div class="drawer__top"><div class="drawer__brand">${e(c.site.menuLabel)}</div><button class="drawer__close" id="drawerClose" aria-label="Close menu">✕</button></div><nav class="drawer__links" aria-label="Mobile">${nav}${resume}<a class="drawer__admin" href="/admin/dashboard" data-drawer-link>${e(c.site.adminLoginLabel || 'Admin login')}</a></nav></div><button class="drawer__backdrop" id="drawerBackdrop" tabindex="-1" aria-hidden="true"></button></aside>
    <main><section class="hero" aria-label="Home"><div class="hero__bg" aria-hidden="true">${image(c.hero.backgroundImage, '', 'hero__image')}<div class="hero__shade" style="opacity:${c.hero.overlay / 100}"></div><div class="hero__vignette"></div><div class="hero__noise"></div><div class="hero__lights"></div></div><div class="container hero__content"><div class="hero__kicker">${e(c.hero.kicker)}</div><h1 class="hero__title">${headline}</h1><p class="hero__subtitle"><span class="type" id="typeTarget" data-roles="${e(c.hero.roles)}">${e(c.hero.roles.split('\n')[0])}</span></p><div class="hero__cta">${buttons(c.hero.buttons)}</div>${c.hero.availability ? `<div class="hero__meta"><div class="pill"><span class="pill__dot"></span>${e(c.hero.availability)}</div></div>` : ''}</div>${c.hero.scrollLabel && c.order.some(id => c[id].settings.enabled) ? `<a class="scrollHint" href="#${c.order.find(id => c[id].settings.enabled)}" aria-label="${e(c.hero.scrollLabel)}"><span class="scrollHint__line"></span><span class="scrollHint__text">${e(c.hero.scrollLabel)}</span></a>` : ''}</section>${c.order.filter(id => c[id].settings.enabled).map(id => sectionHtml[id]()).join('')}</main>
    <footer class="footer"><div class="container footer__inner"><div class="footer__left"><div class="footer__brand">${e(c.footer.name)}</div><div class="footer__muted">${e(c.footer.tagline)}</div></div><div class="footer__right">${c.footer.links.map(l => link(l.label, l.url, '')).join('')}</div></div><div class="footer__bottom"><div class="container footer__bottomInner"><span>© ${new Date().getFullYear()} ${e(c.footer.copyright)}</span>${link(c.site.backToTopLabel, '#top')}</div></div></footer>
    <div class="modal" id="videoModal" aria-hidden="true" role="dialog" aria-modal="true" aria-label="Video player" inert><button class="modal__backdrop" id="modalBackdrop" aria-label="Close video" tabindex="-1"></button><div class="modal__panel" role="document"><button class="modal__close" id="modalClose" aria-label="Close video">✕</button><div class="modal__frame"><iframe id="videoFrame" title="YouTube video player" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen referrerpolicy="strict-origin-when-cross-origin"></iframe></div></div><script src="/scripts/main.js" defer></script></body></html>`;
}

function projectExplorer(c) {
  const rows = c.projects.items;
  if (!rows.length) return empty(c.projects.settings, '');
  const filters = c.projects.filtersEnabled ? `<div class="project-filters"><label>${e(c.projects.searchLabel)}<input type="search" data-project-search placeholder="${e(c.projects.searchLabel)}"></label><label>${e(c.projects.allLabel)}<select data-project-category><option value="">${e(c.projects.allLabel)}</option>${[...new Set(rows.map(p => p.category).filter(Boolean))].map(v => `<option>${e(v)}</option>`).join('')}</select></label></div>` : '';
  return `${filters}<div class="projectsGrid">${rows.map(p => `<article class="projectCard ${p.featured ? 'projectCard--featured' : ''} reveal" data-project-card data-search="${e([p.title,p.description,p.roles,p.category].join(' ').toLowerCase())}" data-category="${e(p.category)}">${image(p.image,p.title,'project-image')}<div class="projectCard__top"><div class="projectCard__tag">${e(p.category)}</div><h3 class="projectCard__title">${e(p.title)}</h3><div class="projectCard__meta">${p.roles.split(',').filter(v => v.trim()).map(v => `<span class="chip">${e(v.trim())}</span>`).join('')}</div></div><p class="projectCard__desc">${e(p.description)}</p><div class="projectCard__foot"><span class="muted">${e(p.duration)}</span><div>${link(c.projects.detailsLabel, '/projects/' + p.slug)} ${link(c.projects.watchLabel,p.url)}</div></div></article>`).join('')}</div><p data-project-empty hidden role="status">${e(c.projects.noResultsLabel)}</p>`;
}
function secondaryPage(c, main) {
  const copy = structuredClone(c); copy.hero.introEnabled = false;
  return renderPortfolio(copy).replace(/<main>[\s\S]*?<\/main>/, `<main class="project-page">${main}</main>`).replace(/href="#/g, 'href="/#');
}
export function renderProjectsPage(c) {
  c = publishedContent(c);
  return secondaryPage(c, section('projects', c.projects.settings, projectExplorer(c)));
}
export function renderProjectPage(c, slug) {
  c = publishedContent(c);
  const p = c.projects.items.find(p => p.slug === slug);
  if (!p) throw new Error('Project not found.');
  const copy = structuredClone(c); copy.site.title = `${p.title} · ${c.site.name}`; copy.site.description = p.description; copy.site.socialImage = p.image;
  const gallery = p.gallery.length ? `<h2>${e(c.projects.galleryLabel)}</h2><div class="gallery-grid">${p.gallery.map(photo => `<figure class="gallery-card">${image(photo.image, photo.alt || photo.caption)}<figcaption>${e(photo.caption)}</figcaption></figure>`).join('')}</div>` : '';
  return secondaryPage(copy, `<section class="section"><div class="container project-story">${link(c.projects.backLabel, '/#projects')}<p class="section__eyebrow">${e(p.category)}</p><h1 class="section__title">${e(p.title)}</h1><p class="section__lead">${e(p.description)}</p><p class="muted">${e(p.roles)} ${e(p.duration)}</p>${image(p.image,p.title,'project-cover')}<div class="project-body">${p.body.split(/\n\s*\n/).map(text => `<p>${e(text)}</p>`).join('')}</div>${link(c.projects.watchLabel,p.url,'btn btn--gold')}${gallery}</div></section>`);
}
