import { createDefaultContent, defaultValue, schema } from '../../scripts/content-model.js';
import { normalizeContent } from '../../server/domain/portfolio.mjs';
export function populatedPortfolio(image='https://example.com/portrait.png',pdf='https://example.com/resume.pdf') {
  const c=createDefaultContent();
  c.site.name='Verification Author'; c.site.brand='Verification Studio'; c.site.title='Verification portfolio'; c.site.description='A test of every section'; c.site.keywords='creative,testing'; c.site.resume=pdf; c.site.socialImage=image;
  c.hero.title='Verification Author'; c.hero.highlight='Author'; c.hero.roles='Director\nEditor'; c.hero.backgroundImage=image; c.hero.overlay=75; c.hero.introEnabled=false;
  c.about.biography='Author biography'; c.about.photo=image; c.about.photoAlt='Author portrait'; c.about.badgeTitle='Creator'; c.about.badgeSubtitle='Independent'; c.about.stats=[{value:'10',label:'Projects'}]; c.about.details=[{title:'Location',description:'Portfolio studio'}]; c.about.buttons=[{label:'Contact author',url:'#contact',style:'ghost'}];
  c.showreel.channelUrl='https://www.youtube.com/@example'; c.showreel.videos=[{...defaultValue(schema.showreel.fields.videos.item),title:'Verification reel',category:'Reel',youtubeUrl:'https://youtu.be/aqz-KE-bpKQ',thumbnail:image,published:true},{...defaultValue(schema.showreel.fields.videos.item),title:'PRIVATE VIDEO'}];
  c.projects.items=[{...defaultValue(schema.projects.fields.items.item),title:'Verification film',description:'A public film',body:'First story paragraph.\n\nSecond story paragraph.',category:'Film',roles:'Director, Editor',duration:'2026',url:'https://www.youtube.com/watch?v=aqz-KE-bpKQ',image,published:true,featured:true,gallery:[{image,alt:'Gallery frame',caption:'Behind the scenes'}]},{...defaultValue(schema.projects.fields.items.item),title:'Verification photo',description:'Photography work',category:'Photography',published:true},{...defaultValue(schema.projects.fields.items.item),title:'PRIVATE PROJECT',body:'Private story'}];
  c.gallery.pictures=[{...defaultValue(schema.gallery.fields.pictures.item),title:'Verification picture',image,caption:'Picture caption',alt:'Gallery picture',published:true},{...defaultValue(schema.gallery.fields.pictures.item),title:'PRIVATE PICTURE'}];
  c.skills.groups=[{title:'Creative skills',items:[{name:'Editing',level:85},{name:'Direction',level:90}]}]; c.experience.items=[{title:'Director role',period:'2024–2026',description:'Timeline description'}];
  c.achievements.items=[{...defaultValue(schema.achievements.fields.items.item),title:'Verification award',description:'Award description',certificate:pdf,links:[{label:'Award details',url:'https://example.com/award'}],published:true},{...defaultValue(schema.achievements.fields.items.item),title:'PRIVATE AWARD'}];
  c.contact.items=[{label:'Email',value:'hello@example.com',url:'mailto:hello@example.com'},{label:'Phone',value:'+910000000000',url:'tel:+910000000000'},{label:'Location',value:'Portfolio studio',url:''}]; c.footer.name=c.site.name; c.footer.copyright=c.site.name; c.footer.links=[{label:'Social profile',url:'https://example.com/profile'}];
  return normalizeContent(c);
}
